# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x07\x61gentic\"z\n\rInvokeRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x0f\n\x07request\x18\x04 \x01(\t\x12\x1b\n\x13not_callable_agents\x18\x05 \x03(\t\"6\n\x0eInvokeResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\"d\n\x13ReturnResultRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08response\x18\x04 \x01(\t\"<\n\x14ReturnResultResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\x32\x8f\x01\n\x05\x41gent\x12\x39\n\x06Invoke\x12\x16.agentic.InvokeRequest\x1a\x17.agentic.InvokeResponse\x12K\n\x0cReturnResult\x12\x1c.agentic.ReturnResultRequest\x1a\x1d.agentic.ReturnResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOKEREQUEST']._serialized_start=24
  _globals['_INVOKEREQUEST']._serialized_end=146
  _globals['_INVOKERESPONSE']._serialized_start=148
  _globals['_INVOKERESPONSE']._serialized_end=202
  _globals['_RETURNRESULTREQUEST']._serialized_start=204
  _globals['_RETURNRESULTREQUEST']._serialized_end=304
  _globals['_RETURNRESULTRESPONSE']._serialized_start=306
  _globals['_RETURNRESULTRESPONSE']._serialized_end=366
  _globals['_AGENT']._serialized_start=369
  _globals['_AGENT']._serialized_end=512
# @@protoc_insertion_point(module_scope)
