# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x07\x61gentic\"K\n\x18ReturnFinalResultRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x16\n\x0e\x66inal_response\x18\x02 \x01(\t\"A\n\x19ReturnFinalResultResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\x32l\n\x0e\x43lientReceiver\x12Z\n\x11ReturnFinalResult\x12!.agentic.ReturnFinalResultRequest\x1a\".agentic.ReturnFinalResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETURNFINALRESULTREQUEST']._serialized_start=25
  _globals['_RETURNFINALRESULTREQUEST']._serialized_end=100
  _globals['_RETURNFINALRESULTRESPONSE']._serialized_start=102
  _globals['_RETURNFINALRESULTRESPONSE']._serialized_end=167
  _globals['_CLIENTRECEIVER']._serialized_start=169
  _globals['_CLIENTRECEIVER']._serialized_end=277
# @@protoc_insertion_point(module_scope)
